import moment from '../../assets/photo/moment.png';

export const films = [
  { title: '33 слова о дизайне', duration: '1ч 42мин', imageUrl: moment },
  { title: 'Тёмные начала', duration: '2ч 15мин', imageUrl: moment },
  { title: 'Суперсемейка', duration: '1ч 55мин', imageUrl: moment },
  { title: 'В поисках Дори', duration: '1ч 37мин', imageUrl: moment },
  { title: 'Шерлок Холмс', duration: '2ч 8мин', imageUrl: moment },
  {
    title: 'Гарри Поттер и философский камень',
    duration: '2ч 32мин',
    imageUrl: moment,
  },
  { title: 'Стражи Галактики', duration: '2ч 1мин', imageUrl: moment },
  { title: 'Интерстеллар', duration: '2ч 49мин', imageUrl: moment },
  { title: 'Криминальное чтиво', duration: '2ч 34мин', imageUrl: moment },
  { title: 'Начало', duration: '2ч 28мин', imageUrl: moment },
  { title: 'Темный рыцарь', duration: '2ч 32мин', imageUrl: moment },
  { title: 'Аватар', duration: '2ч 42мин', imageUrl: moment },
  {
    title: 'Пираты Карибского моря: На краю Света',
    duration: '2ч 49мин',
    imageUrl: moment,
  },
  {
    title: 'Властелин колец: Возвращение Короля',
    duration: '4ч 11мин',
    imageUrl: moment,
  },
  { title: 'Матрица', duration: '2ч 16мин', imageUrl: moment },
  { title: 'Зеленая миля', duration: '3ч 9мин', imageUrl: moment },
  { title: 'Побег из Шоушенка', duration: '2ч 22мин', imageUrl: moment },
  { title: 'Сияние', duration: '2ч 26мин', imageUrl: moment },
  { title: 'Форрест Гамп', duration: '2ч 22мин', imageUrl: moment },
  { title: 'Касабланка', duration: '1ч 42мин', imageUrl: moment },
  { title: 'Славные парни', duration: '2ч 26мин', imageUrl: moment },
  {
    title: 'Терминатор 2: Судный день',
    duration: '2ч 17мин',
    imageUrl: moment,
  },
  { title: 'Достать ножи', duration: '2ч 10мин', imageUrl: moment },
  {
    title: 'Гарри Поттер и Тайная комната',
    duration: '2ч 41мин',
    imageUrl: moment,
  },
  {
    title: 'Звёздные войны: Эпизод IV - Новая Надежда',
    duration: '2ч 1мин',
    imageUrl: moment,
  },
  { title: 'Вспомнить всё', duration: '1ч 53мин', imageUrl: moment },
  { title: 'Гладиатор', duration: '2ч 35мин', imageUrl: moment },
  { title: 'Джуманджи', duration: '1ч 44мин', imageUrl: moment },
  {
    title: 'Гарри Поттер и узник Азкабана',
    duration: '2ч 22мин',
    imageUrl: moment,
  },
  { title: 'Крепкий орешек', duration: '2ч 12мин', imageUrl: moment },
  {
    title: '10 вещей, которых я в тебе ненавижу',
    duration: '1ч 37мин',
    imageUrl: moment,
  },
  { title: 'Холодное сердце', duration: '1ч 42мин', imageUrl: moment },
  { title: 'Король Лев', duration: '1ч 28мин', imageUrl: moment },
  { title: 'Водная мудрость', duration: '1ч 50мин', imageUrl: moment },
  { title: 'Чудо на Гудзоне', duration: '1ч 45мин', imageUrl: moment },
];
